### ISSUE TITLE
README vs GitHub Wiki

### ISSUE THREAD

**Issue by Draydrew** [RNFDigital/rnf-engineering-handbook#14]
For a handbook like this, wouldn't it make more sense to use the Wiki feature so we can split it into pages etcetera?

I guess there is the problem of being unable to do a Pull Request on a wiki page directly though.

I've created an example on the Wiki page with how I'd expect it would look. The README already has clearly defined sections so it was a simple process.

**Comment by jdmunro** [comment]
I think not having PRs on the wiki would be a deal breaker as we'd have no way to agree on changes before they're made.

**Comment by Draydrew** [comment]
There's the option of using the README as before and then just duplicating entries into the Wiki. I'd be happy to do that although then we just have two of the same thing so I guess it'd be a bit pointless. Depends if the extra organisation is worth the (small) hassle.

**Comment by jdmunro** [comment]
You can also split the README into pages btw. Just create new MD files and link to them 👍

**Comment by Draydrew** [comment]
Ah so you can. That is pretty much the same effect...

**Comment by DaleJefferson** [comment]
I think the wiki is stored in Git but it's not exposed to us, it's nice to have the PRs and the history.

I'm going to close this issue
