### ISSUE TITLE
Prefer idiomatic examples

### ISSUE THREAD

**Issue by jdmunro** [RNFDigital/rnf-engineering-handbook#3]
I reckon we'd benefit from making the examples more idiomatic. The problem with foo/bar etc is they can be quite abstract and it also leaves plenty of room for different interpretations. I'm not sure how well these work for our international developers either.

**Comment by DaleJefferson** [comment]
How about we merge #5 and then rework it into something simple but realistic.

**Comment by jdmunro** [comment]
Sure!
